#http://cloud.spring.io/spring-cloud-static/Finchley.SR1/multi/multi_spring-cloud-zookeeper-config.html
##connectString: 192.168.1.186:2181,192.168.1.187:2181,192.168.1.188:2181
spring:
  cloud:
    zookeeper:
      discovery:
        instancePort: ${server.port}
        instanceHost: localhost
        enabled: true
      connectString: 192.168.3.107:2181,192.168.3.108:2181,192.168.3.109:2181
      
---
spring:
  sleuth:
    sampler: 
      probability: 1.0
      
---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: KAFKA
    
---
spring:
  kafka:
    bootstrap-servers:
      - 192.168.3.107:9092
      - 192.168.3.108:9092
      - 192.168.3.109:9092
    