server: 
  port: 8311

spring:
  cloud:
    zookeeper:
      discovery:
         register: false
      connectString: 192.168.3.107:2181,192.168.3.108:2181,192.168.3.109:2181
      
---
spring: 
  application: 
    name: gateway-dev
    
---
spring:
  sleuth:
    sampler: 
      probability: 1.0
      
---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: rabbit
    
---
spring:
  rabbitmq:
    addresses: 192.168.3.50
    port: 5672
    username: admin
    password: admin
    virtual-host: sleuth
    
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cas-client
        uri: lb://cas-client
        predicates:
        - Path=/login/**

      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@remoteAddrKeyResolver}"
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 5

---
spring:
  redis:
    host: localhost
    port: 6379
    database: 0