server: 
  port: 8311

##connectString: 192.168.1.186:2181,192.168.1.187:2181,192.168.1.188:2181
spring:
  cloud:
    zookeeper:
      discovery:
         register: false
      connectString: 192.168.42.186:2181,192.168.42.187:2181,192.168.42.188:2181
      
---
spring: 
  application: 
    name: gateway-zuul
    
---
spring:
  sleuth:
    sampler: 
      probability: 1.0
      
---
spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: KAFKA
    
---
spring:
  kafka:
    bootstrap-servers:
      - 192.168.42.186:9092
      - 192.168.42.187:9092
      - 192.168.42.188:9092
---
zuul:
  routes:
    userdetails:
      path: /user/**
      serviceId: user-service
      ##stripPrefix: false
      
hystrix:
  command:
    default: 
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000