server: 
  port: 8311

spring:
  cloud:
    zookeeper:
      discovery:
         register: false
      connectString: 192.168.188.107:2181,192.168.188.108:2181,192.168.188.109:2181
      
---
spring: 
  application: 
    name: gateway-zuul
    
---
spring:
  sleuth:
    sampler: 
      probability: 1.0
      
---
spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: RABBIT
    
---
spring:
  rabbitmq:
    addresses: 192.168.188.19
    port: 5672
    username: admin
    password: admin
    virtual-host: sleuth
    
---
zuul:
  routes:
    userdetails:
      path: /user/**
      serviceId: user-service
      ##stripPrefix: false
      
hystrix:
  command:
    default: 
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000