server:
  port: 8392

spring:
  cloud:
    zookeeper:
      connectString: 192.168.3.127:2181,192.168.3.128:2181,192.168.3.129:2181

---
spring:
  sleuth:
    sampler: 
      probability: 1.0
      
---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: RABBIT
    
---
spring:
  rabbitmq:
    addresses: 192.168.3.40
    port: 5672
    username: admin
    password: admin
    virtual-host: sleuth
---
spring: 
  application: 
    name: user-service
    