server:
  port: 8392

spring:
  cloud:
    zookeeper:
      connectString: 192.168.3.107:2181,192.168.3.108:2181,192.168.3.109:2181

---
spring:
  sleuth:
    sampler: 
      probability: 1.0
      
---
spring:
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: KAFKA
    
---
spring:
  kafka:
    bootstrap-servers:
      - 192.168.3.107:9092
      - 192.168.3.108:9092
      - 192.168.3.109:9092
    
---
spring: 
  application: 
    name: user-service
    